apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvs
  template:
    metadata:
      labels:
        app: nvs
    spec:
      containers:
      - image: okteto.dev/nvs:latest
        name: nvs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d75d9eb4-ebc0-4336-b633-bd57d121916c"
        - name: Vless_Path
          value: "/g43gjyu"
        - name: Vmess_UUID
          value: "d75d9eb4-ebc0-4336-b633-bd57d121916c"
        - name: Vmess_Path
          value: "/f5u56jutd"
        - name: Share_Path
          value: "/v2link"
